apiVersion: v1
kind: Pod
metadata:
  name: argocd-app-simulation
  labels:
    app: httpd
    libor: testing
  namespace: openshift-gitops
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      command: [ "sleep" ]
      args: [ "infinity" ]
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

